meta_product_name: "ConnecTrainer"
meta_title: "ConnecTrainer"
meta_description: "ConnecTrainer helps you find the find the best personal trainers and instructors in Tokyo who are passionate about what they do.  Get better at what you love to do or try something you've always dreamed of.  Join one of the hundreds of scheduled sessions or connect with a trainer and schedule your own - ConnecTrainer is here to help!"
meta_image: "landing_page_banner.jpg"
